name: Deploy on Server

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
<<<<<<< HEAD
        username: "Juliakp1"
=======
        username: "ezambomsantana"
>>>>>>> cf88a3523ff4acffd9ac371982d6c05daf145bbf
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
<<<<<<< HEAD
        tags: Juliakp1/insper-ci-cd:${{ github.sha }}
=======
        tags: ezambomsantana/partida-06-ci:${{ github.sha }}
>>>>>>> cf88a3523ff4acffd9ac371982d6c05daf145bbf
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_TEST }}
        username: "ec2-user"
        key: ${{ secrets.KEY_TEST }}
        port: 22
        script: |
          docker stop partida-aula
          docker rm --force partida-aula
<<<<<<< HEAD
          docker run  -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} -d -p 8080:8080 --name partida-aula Juliakp1/insper-ci-cd:${{ github.sha }}
          
=======
          docker run  -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} -d -p 8080:8080 --name partida-aula ezambomsantana/partida-06-ci:${{ github.sha }}
          
>>>>>>> cf88a3523ff4acffd9ac371982d6c05daf145bbf
